name = "CosmoCorr"
uuid = "b37e267f-d1fb-4569-8e6b-1de97842933d"
authors = ["Daniel Forero <daniel.forerosanchez@epfl.ch> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
